networks:
  ethereum:
    rpc: "https://ethereum-mainnet-rpc.allthatnode.com"
    token_messenger: "0xBd3fa81B58Ba92a82136038B25aDec7066af3155"
    message_transmitter: "0x0a992d191DEeC32aFe36203Ad87D7d289a738F81"
  noble:
    rpc: "https://rpc.mainnet.noble.strange.love"
    destination_id: 1 # TODO: Change this once deployed.

indexer:
  start_block: 16730029
  attestation_base_url: "https://iris-api.circle.com/attestations/"
  valid_token_addresses: [
    "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" # USDC
  ]
