networks:
  ethereum:
    rpc: "https://ethereum-mainnet-rpc.allthatnode.com"
    token-messenger: "0xBd3fa81B58Ba92a82136038B25aDec7066af3155"
    message-transmitter: "0x0a992d191deec32afe36203ad87d7d289a738f81"
  noble:
    rpc: "https://noble-rpc.polkachu.com"
    destination-id: 1 # TODO what is this for Noble?

indexer:
  start-block: 17312317
  attestation-base-url: "https://iris-api.circle.com/attestations/"
  valid-token-addresses: [
    '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' # USDC
  ]