networks:
  source:
    ethereum:
      enabled: true
      domain-id: 0
      rpc: "wss://goerli.infura.io/ws/v3/<key>"
      message-transmitter: "0x26413e8157CD32011E726065a5462e97dD4d03D9"
      request-queue-size: 1000
      start-block: 0 # set to 0 to default to latest block
      lookback-period: 20 # historical blocks to look back on launch
  destination:
    noble:
      domain-id: 4
      api: "https://api.testnet.noble.strange.love:443"
      rpc: "https://rpc.testnet.noble.strange.love:443"
      chain-id: "grand-1"
      gas-limit: 200000
      broadcast-retries: 5 # number of times to attempt the broadcast
      broadcast-retry-interval: 5 # time between retries in seconds
      filter-forwards-by-ibc-channel: false
      forwarding-channel-whitelist:
        - "channel-10" # osmo-test-5
        - "channel-15" # dydx-testnet-2

  # source domain id -> destination domain id
  enabled-routes:
    0: 4 # ethereum to noble
  # destination domain -> minter metadata
  minters:
    4:
      minter-address: "noble1...."
      minter-mnemonic: "12345" # hex encoded
circle:
  attestation-base-url: "https://iris-api-sandbox.circle.com/attestations/"
  fetch-retries: 10 # additional times to fetch an attestation
  fetch-retry-interval: 10 # time between retries in seconds
processor-worker-count: 16
